name: React Todo
on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:  # Define a job named 'build'
    runs-on: macos-latest  # Specify the runner environment (Ubuntu latest)

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Set up Node.js with a specified version
        with:
          node-version: '20.x' # Example: Use Node.js version 20 (adjust if needed)

      - name: Install dependencies
        run: npm ci  # Install project dependencies using npm ci

      - name: Build React app
        run: npm run build  # Build the React application

      # Optional: Add testing steps here (e.g., unit tests)
      # - name: Run tests
      #   run: npm test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4  # Upload the build files as an artifact
        with:
          name: build  # Name of the artifact
          path: build  # Path to the build directory

  deploy:  # Define a job named 'deploy'
    needs: build  # Ensure the deploy job runs after the build job
    runs-on: macos-latest  # Specify the runner environment

    steps:
      - uses: actions/checkout@v3  # Checkout the source code again

      - name: Download build artifact
        uses: actions/download-artifact@v4 # Download the build artifact from the build job
        with:
          name: build # Name of the artifact

      # Example: Deploy to GitHub Pages (replace with your deployment method)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  # Use a pre-built action for GitHub Pages deployment
        with:
          branch: gh-pages  # Specify the branch to deploy to (commonly 'gh-pages' for GitHub Pages)
          folder: build  # Specify the folder containing the build files
