name: React Todo
on:
  push:
    branches:
      main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      main  # Trigger the workflow on pull requests to the main branch

jobs:
  build_and_deploy:  # Define a job named 'build'
    runs-on: macos-latest  # Specify the runner environment (Ubuntu latest)

    steps:
      - uses: actions/checkout@v4  # Checks out the source code repository
      - name: Set up Node.js
        uses: actions/setup-node@v4  # Set up Node.js with a specified version
        with:
          node-version: '20.x' # Example: Use Node.js version 20 (adjust if needed)

      - name: Install dependencies
        run: npm install
      - name: Build React app
        run: npm run build  # Build the React application

      # Optional: Add testing steps here (e.g., unit tests)
      # - name: Run tests
      #   run: npm test
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Uses the default GitHub token
          publish_dir: ./build
